#!/usr/bin/env python

from collections import namedtuple
from pathlib import Path
from shutil import copy as copyfile, copytree
from tempfile import TemporaryDirectory
from zipapp import create_archive


Versions = namedtuple('Versions', ('zipapp', 'paper', 'rfbs', 'python'))
default_versions = Versions('0.1.0', '0.1.0', '0.1.0', 'py3-none-any')


def copy_wheel(src, dst, name, version, tags):
    wheel_name = f'{name}-{version}-{tags}.whl'
    dst.mkdir(exist_ok=True)
    copyfile(src / name / 'dist' / wheel_name, dst / wheel_name)


def build_zipapp(src, dst, versions):
    copytree(src / 'bootstrap', dst, dirs_exist_ok=True)
    copy_wheel(src, dst, 'paper_ui', versions.paper, versions.python)
    copy_wheel(src, dst, 'rfbs', versions.rfbs, versions.python)
    copyfile(src / 'install.py', dst / '__main__.py')


def write_zipapp(src, dst, versions, interpreter):
    name = f'install-paper-{versions.zipapp}-for-{versions.python}.pyz'
    where = dst / 'dist'
    where.mkdir(parents=True, exist_ok=True)
    create_archive(src, target=(where / name), interpreter=interpreter)


def main(versions):
    here = Path(__file__).parent
    with TemporaryDirectory() as there:
        there = Path(there)
        build_zipapp(here, there, versions)
        write_zipapp(there, here, versions, '/usr/bin/env python')


if __name__ == '__main__':
    main(default_versions)
