#!/usr/bin/env python
import sys
from time import time
from pathlib import Path
current_executable = Path(sys.executable).absolute()
here = Path(__file__).parent.absolute()
my_executable = here / 'python'

if current_executable != my_executable:
    import subprocess
    print([my_executable, *sys.argv])
    sys.exit(subprocess.call([my_executable, *sys.argv]))
import configparser
p = configparser.ConfigParser()
with open(here / '..' / 'entry_points.txt') as f:
    p.read_file(f)
module, colon, func = p['console_scripts'][sys.argv[1]].partition(':')
sys.argv = sys.argv[2:]
import importlib
module = importlib.import_module(module)
if colon:
    getattr(module, func)()
